# Generated by Django 4.0.6 on 2022-08-06 10:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('jobapp', '0002_postjob_user_remove_profile_email'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='cpassword',
        ),
    ]
