# Generated by Django 4.0.6 on 2022-08-09 08:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobapp', '0003_remove_user_cpassword'),
    ]

    operations = [
        migrations.CreateModel(
            name='ulog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=20)),
                ('password', models.CharField(max_length=10)),
            ],
        ),
        migrations.RenameModel(
            old_name='user',
            new_name='userr',
        ),
    ]
