# Generated by Django 4.0.6 on 2022-08-11 03:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('jobapp', '0004_ulog_rename_user_userr'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ulog',
        ),
    ]
