# Generated by Django 4.0.6 on 2022-08-17 19:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobapp', '0005_delete_ulog'),
    ]

    operations = [
        migrations.CreateModel(
            name='applyjobmodel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fullname', models.CharField(max_length=30)),
                ('jobtitle', models.CharField(max_length=30)),
                ('phone', models.IntegerField()),
                ('email', models.EmailField(max_length=254)),
                ('qualification', models.CharField(max_length=150)),
                ('passingyear', models.IntegerField()),
                ('skills', models.CharField(max_length=300)),
                ('relocate', models.CharField(choices=[('yes', 'yes'), ('no', 'no')], max_length=30)),
                ('pdone', models.CharField(max_length=800)),
                ('resume', models.FileField(upload_to='jobapp/static')),
                ('companyname', models.CharField(max_length=50)),
            ],
        ),
    ]
